// Generated by Cypress Author on 2026-08-13.
// @no-ensureAuthenticated — the All Products listing is a public page; no login is required.

describe("Products listing", () => {
  it(
    "[AE-PRODUCTS-001] anonymous visitor opens the products route → sees a non-empty All Products grid",
    { tags: ["@AE-PRODUCTS-001", "@smoke", "@P0"] },
    () => {
      cy.visitProducts();
      cy.assertProductsListingVisible(1);
    },
  );
});
